//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iQueue.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iQueue.db")]
        public string dbFilePath {
            get {
                return ((string)(this["dbFilePath"]));
            }
            set {
                this["dbFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int webServicePort {
            get {
                return ((int)(this["webServicePort"]));
            }
            set {
                this["webServicePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logs")]
        public string logDirectoryPath {
            get {
                return ((string)(this["logDirectoryPath"]));
            }
            set {
                this["logDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool serverAutoStart {
            get {
                return ((bool)(this["serverAutoStart"]));
            }
            set {
                this["serverAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string webServiceAddress {
            get {
                return ((string)(this["webServiceAddress"]));
            }
            set {
                this["webServiceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("status")]
        public string statusDirectoryPath {
            get {
                return ((string)(this["statusDirectoryPath"]));
            }
            set {
                this["statusDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ledThreadsAutoStart {
            get {
                return ((bool)(this["ledThreadsAutoStart"]));
            }
            set {
                this["ledThreadsAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("templates")]
        public string tplDirPath {
            get {
                return ((string)(this["tplDirPath"]));
            }
            set {
                this["tplDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BEGIN TRANSACTION;\r\nCREATE TABLE [events] (\r\n  [date] DATETIME NOT NULL DEFAULT (" +
            "datetime(CURRENT_TIMESTAMP, \'localtime\')), \r\n  [user] VARCHAR NOT NULL, \r\n  [vis" +
            "itor] VARCHAR NOT NULL, \r\n  [action] VARCHAR NOT NULL);\r\n\r\n\r\nCREATE TABLE [scree" +
            "ns] (\r\n  [id] INTEGER PRIMARY KEY AUTOINCREMENT, \r\n  [name] VARCHAR NOT NULL, \r\n" +
            "  [ip] VARCHAR(20), \r\n  [port] INTEGER NOT NULL DEFAULT 5005, \r\n  [behavior] INT" +
            "EGER NOT NULL DEFAULT 0, \r\n  [width] INTEGER DEFAULT 160, \r\n  [height] INTEGER D" +
            "EFAULT 48);\r\n\r\n\r\nCREATE TABLE [settings] (\r\n  [id] INTEGER NOT NULL PRIMARY KEY " +
            "AUTOINCREMENT, \r\n  [user] INTEGER NOT NULL DEFAULT 0, \r\n  [screen] INTEGER NOT N" +
            "ULL DEFAULT 0, \r\n  [key] VARCHAR(128) NOT NULL, \r\n  [name] VARCHAR(1024), \r\n  [v" +
            "alue] TEXT, \r\n  [type] VARCHAR NOT NULL DEFAULT text);\r\n\r\nCREATE UNIQUE INDEX [s" +
            "ettUniq] ON [settings] ([user], [screen], [key]);\r\nINSERT INTO \"settings\" VALUES" +
            "(1,0,0,\'playSound\',\'Проигрывать звук (1-да, 0-нет)\',\'1\',\'number\');\r\nINSERT INTO " +
            "\"settings\" VALUES(2,0,0,\'setExpiryTimeout\',\'Пометить заказ как задержанный через" +
            ", минут\',\'15\',\'number\');\r\nINSERT INTO \"settings\" VALUES(3,0,0,\'doneVisibleTimeou" +
            "t\',\'Отображение номера после готовности, минут\',\'1\',\'number\');\r\nINSERT INTO \"set" +
            "tings\" VALUES(4,0,0,\'stuntCode\',\'Эффект анимации (формат HEX: STRING)\',\'0x05: MO" +
            "VE_UP\',\'text\');\r\nINSERT INTO \"settings\" VALUES(5,0,0,\'scrollSpeed\',\'Коэффициент " +
            "замедления анимации\',\'20\',\'number\');\r\nINSERT INTO \"settings\" VALUES(6,0,0,\'scrol" +
            "lDelay\',\'Время отображения кадра на экране, секунд\',\'0\',\'number\');\r\nINSERT INTO " +
            "\"settings\" VALUES(7,0,0,\'fontFamily\',\'Шрифт текста на экранах\',\'Tahoma\',\'text\');" +
            "\r\nINSERT INTO \"settings\" VALUES(8,0,0,\'fontSize\',\'Размер шрифта на экранах, pt\'," +
            "\'10\',\'number\');\r\nINSERT INTO \"settings\" VALUES(9,0,0,\'ledRefreshTimeout\',\'Период" +
            "ичность обновления экранов, секунд\',\'15\',\'number\');\r\n\r\n\r\n\r\n\r\nCREATE TABLE [users" +
            "] (\r\n[id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, \r\n[login] VARCHAR(128) NOT" +
            " NULL ON CONFLICT FAIL, \r\n[password] VARCHAR(32) NOT NULL, \r\n[role] INT(2) NOT N" +
            "ULL DEFAULT 0);\r\n\r\nCREATE UNIQUE INDEX [loginUniq] ON [users] ([login]);\r\nINSERT" +
            " INTO \"users\" VALUES(1,\'admin\',\'21232f297a57a5a743894a0e4a801fc3\',100);\r\n\r\nCREAT" +
            "E TABLE [visitors] (\r\n  [id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, \r\n  [nu" +
            "mber] VARCHAR NOT NULL, \r\n  [status] INTEGER NOT NULL DEFAULT 0, \r\n  [start] DAT" +
            "ETIME NOT NULL DEFAULT (datetime(CURRENT_TIMESTAMP, \'localtime\')), \r\n  [done] DA" +
            "TETIME, \r\n  [end] DATETIME);\r\n\r\nCREATE TRIGGER [newVisitor]\r\nAFTER INSERT\r\nON [v" +
            "isitors]\r\nFOR EACH ROW\r\nBEGIN\r\n  INSERT INTO events (user,visitor,action) VALUES" +
            " (\'admin\',new.number,\'Добавлен новый талон\');\r\nEND;\r\n\r\nCREATE TRIGGER [endVisito" +
            "r]\r\nAFTER UPDATE OF [status]\r\nON [visitors]\r\nFOR EACH ROW\r\nWHEN new.status=2 AND" +
            " old.status!=2\r\nBEGIN\r\n    INSERT INTO events (user,visitor,action) VALUES (\'adm" +
            "in\',new.number,\'Статус заказа по талону изменился на ГОТОВ.\');    \r\nEND;\r\n\r\nCREA" +
            "TE TRIGGER [delVisitor]\r\nAFTER UPDATE OF [status]\r\nON [visitors]\r\nFOR EACH ROW\r\n" +
            "WHEN new.status=-1 AND old.status!=-1\r\nBEGIN\r\n  INSERT INTO events (user,visitor" +
            ",action) VALUES (\'admin\',new.number,\'Талон отмечен на удаление.\');\r\nEND;\r\n\r\nCREA" +
            "TE TRIGGER [dropVisitor]\r\nAFTER DELETE\r\nON [visitors]\r\nFOR EACH ROW\r\nBEGIN\r\n INS" +
            "ERT INTO events (user,visitor,action) VALUES (\'admin\',old.number,\'Удален талон.\'" +
            ");\r\nEND;\r\n\r\nCREATE TRIGGER [lateVisitor]\r\nAFTER UPDATE OF [end]\r\nON [visitors]\r\n" +
            "FOR EACH ROW\r\nBEGIN\r\n INSERT INTO events (user,visitor,action) VALUES (\'admin\',n" +
            "ew.number,\'Заказ по талону обслуживался \'||(strftime(\'%M\',new.end) - strftime(\'%" +
            "M\',old.start))||\' минут\' );\r\nEND;\r\nCOMMIT;")]
        public string initialDBStructure {
            get {
                return ((string)(this["initialDBStructure"]));
            }
            set {
                this["initialDBStructure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool softActivated {
            get {
                return ((bool)(this["softActivated"]));
            }
            set {
                this["softActivated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string softCode {
            get {
                return ((string)(this["softCode"]));
            }
            set {
                this["softCode"] = value;
            }
        }
    }
}
